name: memory_game
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bot_toast: ^4.0.1
  provider: ^6.0.2
  easy_localization: ^3.0.0
  chaotic: ^3.10.8
  animate_do: ^2.1.0
  flutter_svg: ^1.0.3

dev_dependencies:
  chaotic_helper:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/animals/
    - assets/lang/
